(custom-set-variables
 ;; custom-set-variables was added by Custom.
 '(custom-safe-themes (quote ("8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" default)))
 '(inhibit-startup-screen t))

(require 'cask "~/git/cask/cask.el")
(cask-initialize)

(evil-mode 1)
(yas-global-mode 1)
(ido-mode 1)
(ido-everywhere 1)
(ido-ubiquitous-mode 1)
(setq ido-enable-flex-matching t)
(flx-ido-mode 1)
(setq ido-use-faces nil)
(require 'smartparens-config)
(smex-initialize)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'execute-extended-command)
(add-to-list 'auto-mode-alist '("\\.text\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . markdown-mode))
(pending-delete-mode t)
(require 'emmet-mode)
(require 'ac-dabbrev)
(add-hook 'after-init-hook #'global-flycheck-mode)
(load (f-expand "flycheck-ghcmod.el" user-emacs-directory))
(eval-after-load 'flycheck
  '(require 'flycheck-ghcmod))
;;(autoload 'ghc-init "ghc" nil t)
;;(add-hook 'haskell-mode-hook (lambda () (ghc-init) (flymake-mode)))
;;(add-hook 'haskell-mode-hook (lambda () (ghc-init) ))
(when (require 'auto-complete-config)
  (ac-config-default)
  (add-to-list 'ac-sources 'ac-source-yasnippet 'ac-source-dabbrev))
(global-auto-complete-mode 1)
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
(add-hook 'haskell-mode-hook 'turn-on-hi2)
(add-hook 'haskell-mode-hook '(subword-mode +1))
(add-to-list 'completion-ignored-extensions ".hi")
(setq gc-cons-threshold 20000000)
(require 'fsharp-mode)
(setq inferior-fsharp-program "/usr/local/bin/fsharpi --readline-")
(setq fsharp-compiler "/usr/local/bin/fsharpc")
(setq fsharp-ac-use-popup 1)
(setq fsharp-doc-idle-delay 1)
(setq fsharp-ac-intellisense-enabled 1)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
)
